import './globals.css';
import Script from 'next/script';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { GA_TRACKING_ID } from '@/lib/gtag';

export const metadata = {
  title: 'nexus app',
  description: 'Generated by create next app with agent enhancements',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}`}
        />
        <Script
          id="gtag-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', '${GA_TRACKING_ID}', {
                page_path: window.location.pathname,
              });
            `,
          }}
        />
      </head>
      <body className="flex flex-col min-h-screen bg-[var(--color-background-default)] text-slate-900 antialiased">
        <Header />
        
        {/* 
          Main content wrapper: 
          - pt-20 to account for fixed header height
          - flex-grow to push footer to the bottom of the viewport
          - overflow-x-hidden to prevent horizontal scrollbars from entrance animations
        */}
        <div className="flex-grow pt-20 overflow-x-hidden">
          {children}
        </div>

        <Footer />

        {/* Agent Widget Script */}
        <Script src="/agent-widget.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
