import './globals.css';
import Script from 'next/script';
import Header from '@/components/Header';

export const metadata = {
  title: 'nexus app',
  description: 'Generated by create next app with agent enhancements',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {/* Main content wrapper to prevent horizontal overflow and center content on large screens */}
        <div className="pt-20 mx-auto max-w-screen-2xl">
          {children}
        </div>

        {/* Agent Widget Script (as suggested by its comment) */}
        <Script src="/agent-widget.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
