import './globals.css';
import Script from 'next/script';

export const metadata = {
  title: 'Next.js Agent Project',
  description: 'Generated by create next app with agent enhancements',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}

        {/* Agent Widget Script (as suggested by its comment) */}
        <Script src="/agent-widget.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
